### ISSUE TITLE
Maybe implement RequestBody#empty?

### ISSUE THREAD

**Issue by adstage-david** [celluloid/reel#109]
Just upgraded to Webmachine 1.2.1+Reel 0.4.0 and found that request.body was now returning Reel RequestBody objects no matter what. This breaks the way `request.has_body?` works in webmachine, since RequestBody doesn't respond to `#empty?`:

https://github.com/seancribbs/webmachine-ruby/blob/master/lib/webmachine/request.rb#L39

Easy enough to work around in my code, but maybe a function should be added so that `#has_body?` can return the right value in webmachine?

**Comment by digitalextremist** [comment]
Released in 0.6.0.pre1
