### ISSUE TITLE
Update benchmarks in README.md

### ISSUE THREAD

**Issue by pinyin** [celluloid/reel#171]
Current benchmark results in master/README.md seems to be present since Dec, 2012

https://github.com/celluloid/reel/commit/471b14d5c876344b2c6da384658906b0d804d1a8

I notice there was several bugs fixed since then

https://groups.google.com/forum/#!topic/celluloid-ruby/D-7fXYaBswU

Does that mean the benchmarks are outdated?

**Comment by tarcieri** [comment]
The benchmarks are ancient and should probably just be removed.

**Comment by digitalextremist** [comment]
Removed in `0.6.0`
