### ISSUE TITLE
Server::HTTP produces: Error accepting SSLSocket: IOError: closed stream

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/reel#177]
This build error is blocking #174 ( #176 ) under jruby only.

**Comment by digitalextremist** [comment]
The issue here is interesting. Under jRuby, the errors are happening as they do under Rubinius... the only difference is that when the program is terminated, suddenly a backlog of messages want to output, and that I believe is causing the build to error.

**Comment by tarcieri** [comment]
@digitalextremist this might be because Celluloid doesn't properly implement log-flushing. By default Ruby buffers messages in userspace

**Comment by digitalextremist** [comment]
@tarcieri This issue also happens however, when no connections at all are made to the server..

**Comment by digitalextremist** [comment]
Seems like a problem with `jruby-openssl` @headius

I'm testing this with `1.7.16.1` and using `jruby-openssl-java-1.9.6`

About to try `1.7.19` and `jruby-head`

**Comment by digitalextremist** [comment]
This does also happen with `1.7.19`
Retesting with `jruby-head` which I'd imagine is `9k`

**Comment by digitalextremist** [comment]
New, clearer message: `SSLSocket: IOError: Writing not possible during handshake`

**Comment by digitalextremist** [comment]
Wow. There's all kinds of new-bad going on with `jruby-9.0.0.0-pre1`
The test-client can't hit the server more than 23 or so times before the server locks completely.

**Comment by digitalextremist** [comment]
This was resolved.
