### ISSUE TITLE
Rename Reel. The self-answering Issue.

### ISSUE THREAD

**Issue by digitalextremist** [celluloid/reel#192]
Before we have massive uptake and take over > 51% of the HTTP/HTTP/WS/WSS/SSE market share...

I've been thinking about the type of strategic/organizational issue that came up in celluloid/celluloid-dns#4 which hits the same issue I've been seeing with `Reel` ... it really ought to be either:

* `celluloid-io-web`
* `celluloid-web`
* `celluloid/web` ( my favorite )

# But

wtf does `web` mean? I can't stand behind it as a word... so the whole thing falls apart right there...

The end-result answer is that it really should be `celluloid/reel` because, "celluloid" means:

> "A colorless flammable material made from nitrocellulose and camphor and used to make photographic film."

... and `Reel` is where that raw material results in a presentation-level display... in stills, in streams, etc. Whatever the hell the web is, `Reel` does describe. So it's a better generic term than `web` *and* it is consistent with the underlying brand.

Open, closed.

**Comment by tarcieri** [comment]
> "A dizzying lifetime... reeling by on celluloid" _-- Rush / Between The Wheels_

Enough said :wink:
