### ISSUE TITLE
http v1.0.0.pre1 breaks reel

### ISSUE THREAD

**Issue by benlangfeld** [celluloid/reel#213]
See https://travis-ci.org/adhearsion/adhearsion/jobs/95312317.

**Comment by bklang** [comment]
This seems to already be [fixed in reel](https://github.com/celluloid/reel/blob/master/lib/reel/response.rb#L10), we just need a new release made for reel.

**Comment by digitalextremist** [comment]
Roger that. Working on preparing `0.6.0` release to be cut.

**Comment by benlangfeld** [comment]
@digitalextremist What can I do to help get 0.6.0 out?

**Comment by digitalextremist** [comment]
@benlangfeld you could deprecate pre-0.17.0 `Celluloid` references, probably mostly in the examples. Also, general testing with post-0.17.0 `Celluloid` code. I'll inventory the rest of what's needed, and I'm coming to this before everything else needed in the celluvoid, over the next two weeks.

**Comment by jlyonsmith** [comment]
:+1:  Please can we have a new release soon?

**Comment by tarcieri** [comment]
We should probably cut a release of this

**Comment by digitalextremist** [comment]
Was delayed over the holidays, but still preparing this shortly

**Comment by bklang** [comment]
@digitalextremist Any update on this? Anything I can do to help with the release?

**Comment by tarcieri** [comment]
I can do a release if need be

**Comment by jlyonsmith** [comment]
That would be awesome Tony.

On Mon, Feb 1, 2016 at 3:22 PM, Tony Arcieri <notifications@github.com>
wrote:

> I can do a release if need be
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/celluloid/reel/issues/213#issuecomment-178251479>.
>



-- 
John Lyon-Smith
john@lyon-smith.org
@jlyonsmith
360 860 1883

**Comment by rmc3** [comment]
+1 for a release, please!

**Comment by tarcieri** [comment]
PR to release 0.6.0 here:

https://github.com/celluloid/reel/pull/219

**Comment by tarcieri** [comment]
Reel 0.6.0 has been released. I'll post an announcement shortly.
