### ISSUE TITLE
0.6.0 release can't ping websocket clients

### ISSUE THREAD

**Issue by kenichi** [celluloid/reel#222]
can we cut a 0.6.1 with the no rack PR in it? it also contains a forward to websocket-driver's ping, so that reel servers can ping websocket clients without having to do any instance_variable_get :@driver stuff.

angelo, in its endeavor to make websockets "easy", sets up automatic ping tasks on the reactor when websockets connect, and they crash on 0.6.0:

```
E, [2016-03-10T09:58:13.845297 #77156] ERROR -- : Actor crashed!
NoMethodError: undefined method `ping' for #<Reel::WebSocket:0x007fa2d5884ee0>
```

**Comment by tarcieri** [comment]
Yes, will do this this weekend

**Comment by tarcieri** [comment]
0.6.1 released

**Comment by kenichi** [comment]
awesome. thanks!
